# 数据源配置
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        druid:
            master:
                # 主库数据源
                url: jdbc:mysql://127.0.0.1:3306/miner?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
                username: root
                password: 45545
            # 从库数据源
            slave:
                # 从数据源开关/默认关闭
                enabled: false
                url:
                username:
                password:
            # 初始连接数
            initialSize: 5
            # 最小连接池数量
            minIdle: 10
            # 最大连接池数量
            maxActive: 20
            # 配置获取连接等待超时的时间
            maxWait: 60000
            # 配置连接超时时间
            connectTimeout: 30000
            # 配置网络超时时间
            socketTimeout: 60000
            # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
            timeBetweenEvictionRunsMillis: 60000
            # 配置一个连接在池中最小生存的时间，单位是毫秒
            minEvictableIdleTimeMillis: 300000
            # 配置一个连接在池中最大生存的时间，单位是毫秒
            maxEvictableIdleTimeMillis: 900000
            # 配置检测连接是否有效
            validationQuery: SELECT 1 FROM DUAL
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            webStatFilter:
                enabled: true
            statViewServlet:
                enabled: true
                # 设置白名单，不填则允许所有访问
                allow:
                url-pattern: /druid/*
                # 控制台管理用户名和密码
                login-username: ruoyi
                login-password: 123456
            filter:
                stat:
                    enabled: true
                    # 慢SQL记录
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true

external:
    hotWallet:
        publicKey: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0ImavjHT2aYGXFfJj+8EDiaIHgJtcTn1O3OCW4qsHlHWOmsPk18wTY71wgT8SSgJDH73mCNgHURj/H2xf2ESSjBI7gh1n7p5r+qmf2O9PULNDnOHgsOY2eEEQDekjxL7NkRItTZm8jU3LUmVOYnXJRVi5LI5wlSwXKvAFGaPBvV+nFra5JDM0b1WNGfj5U7C97PyeSvg0S9sELqjJ9K0L1NQQz83lLu7mHaQigYc0xPKdZ2HaWNrTkI1c/E76gmHx6TQplg3JaqZ47+VD1rIPzufgi+JaY3P232Z+tDJStXRwpqJUvke08v/m/OBPAw4TuhGNyS1UFVCIWmhF46SpQIDAQAB"
        fenkongPubKey: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzN+AxAir3lGYKOtuTxCf9d7vMJQJf16Kz62VhdfyhDrO6WBUXe8v5c/3WNkkB/AtYvNAFkCQ8dQ8etyx3x53mt5wx8R/zVUTCkPQEx0xSYUCxiWe4oVLuws9rm9Z4x5ghkD1ozaga+wYS7+07PGmXLGVhSXmkVERVEu5Jv6dRakYHfrXmkHVOoPAuSsZAnnbjZT+l7nmecO/VBPP3KGfD0soKVIC5qqkA9Fz87ljQDBUx89uAwll1TsxF7JMPxMrJRMJfz/05Z1PfkEKKdnv2GkqER/i3WVhpo17rXkIkcsLW/8Z6RMwQUu5iQ6O6iaSgC/oaY12NXZAv4xjKNcOCQIDAQAB"
        appId: "ca7p84b4mh7xxj4f"
        ownerPriKey: "MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCZ3vsyxkoczHnMKcEdmlScOIPc+Zejx6T3UnR7BGyCc4+iJFiF/+9DuoAtaflizHf3f8gNeqdbjEqei30NRPOPmu3NEvs/ycK6bvBRDWf/AuzJvsBmCc0tqsC925fDp+ziNbAKebhq27M0xDUB0MNnQenf5C5XimQpZg+RF8dzeTxhO2JXsuHHz2T2qq1a0yvzFLVmCGe4qms913h+a2W3bQZ1vXs5VztSzDWTezZTgWv8hPB0dVs8iymlK+W0DA1PD9WLuGXuHHAivpPZN+8fe3na4pKmlNtXq5HW9dOjG1FN7b1SwZZ1EvwHWH9eXEhi7YzH/6yLV19KckHLO9YJAgMBAAECggEAWdJZzxUDlHYkr3K8YbyCocM37png1GGpwhpnFpzJfwlYkm0nI+n4URAg3OHdC7iSW29DZ+LuqTlnIdAJiuJyT6VAJhNriZwMyWoTbS0nRSz+7vIkPCyCkqL36pyypitz08VFY4gUiISBw066JrooJzHKBcGc78tAlw4WDjvUWWpHhiUf2l2OSiDW1bvBN0UpIACLnyx/cNnpuXq/wyzAHXgonurPMPO+s084wB54ufQ45MF6SBTq9W8ZF5AXZtdRSXzMU1eVyIbPyeub3VcuUf+ZfJMpZ+qxq4ggn8gNmX86sB4CVtZwqxMH9cPgrPT1ODDvdGmA5/pBPmfgI1ZHBQKBgQDGxGpWcmdtRq4RMSlMzF9o5oSAPTYRPR2bBH0NPVYvLA595uQyyn7xtJoclXcmXx6JOF19cWB7W8RilUYuLmaJba3ZPRpGH+Efphq4C8WYED2WLPx8MXFf0vp3RO/LCTDMDXEkwqZt9lzMQ7dTxfkA+irfPcbb0S7eLZVjp+aOWwKBgQDGLSnDdnIl7V9WobVIva3LnrJFNS/XiMHCkhEr1q0wv36xTXSpLMJa2TIoTpguff/DrWFRXqQkH4egJWch5FdPSuNvgHbBvcDGphClKMzEB+NjnVN5pzKbtcTuDv9u4pg0wanBINpvDC/rcBDuIlgQCsNBd+8h1SoVAy+0tzbiawKBgQC2++ldThLzIcdrolOAFQGcw+KlYDSfKCFSLY6mGpp18NwigeYA8DRvdbEOsXawR48ICnDe4/pLdk7T5tJl/2d8CxGp1TuT5RNOHI+qcYPlmsXns+B4wNe7vLHCDR+oTfyzTYikq+Glh9EkZw6lu7KheKzxOaERioDYHyTRSqfQ0wKBgQCPUrhikXYKcfrCZ575JZzcp0Ach1O7WD9xXTwn7VFB8SxKRE87zpAdLfl1Zynubdech/ba50xkh50JuCM3QrHWOb30tP6uLXKO+CkPmUtF9sKAF5b4Y3BZZoMu/A/F/QDBHtKLRxxStYiuiFTmNFZl+7Ks1XVPjZ+qpKxK0TpTUwKBgFhJHTRKDNhfRyZwPoQVpjgJQ0v4GN21LpudYt+zhdBuQBYFQNJnRyRHPbTpu9/oOtj6ZGElz48o5NKeyKFThsHWldH6W3BtlzO4NA0eWfm1mUh29CKL3DbfDuqZ0qsNAGY8qjxil8XLVMXeZMgf64oU/HdLId07B4YRc69HrKI5"
        ownerPubKey: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmd77MsZKHMx5zCnBHZpUnDiD3PmXo8ek91J0ewRsgnOPoiRYhf/vQ7qALWn5Ysx393/IDXqnW4xKnot9DUTzj5rtzRL7P8nCum7wUQ1n/wLsyb7AZgnNLarAvduXw6fs4jWwCnm4atuzNMQ1AdDDZ0Hp3+QuV4pkKWYPkRfHc3k8YTtiV7Lhx89k9qqtWtMr8xS1ZghnuKprPdd4fmtlt20Gdb17OVc7Usw1k3s2U4Fr/ITwdHVbPIsppSvltAwNTw/Vi7hl7hxwIr6T2TfvH3t52uKSppTbV6uR1vXToxtRTe29UsGWdRL8B1h/XlxIYu2Mx/+si1dfSnJByzvWCQIDAQAB"
        baseUrl: "https://apitest.hyperbc.pro/shopapi"
